id: P142211D9
initial_creation_type: input
source_metadata:
  title: 'Vasubandhu: Triṃśikāvijñapti'
  language: zh
  volumes:
    9ec34d0a9adc4ea5a1350db9abb20624:
      title: CI_Verses 1-10
      base_file: CI_Verses 1-10.txt
      work_id: W5C055506
    acb5bc484c6a476aa100de67ba45e76c:
      title: CI_Verses 11-20
      base_file: CI_Verses 11-20.txt
      work_id: W559C9EE5
    bfd9e9ca2e2e4afbac13bfc1d832e793:
      title: CI_Verses 21-31
      base_file: CI_Verses 21-31.txt
      work_id: WABA2B0E1
  chapter_to_tile:
    CI: Title
created_at: '2022-03-01T23:28:19.615895'
last_modified_at: '2022-03-01T23:28:19.615902'
